
[package]
    archivePath = "https://d4i3qtqj3r0z5.cloudfront.net/omni.ai.langchain.core-1.2.0%2Blx64.zip"

    [package.target]

        [package.target.platform]
            0 = "linux-x86_64"

    [package.publish]
        kitVersion = "106.4.0+master.149313.164b6eef.gl"
        date = 1733538279
        buildNumber = "2022.2.0-beta.8+master.1487.13a43f11.gl"
        repoName = "kit-template"
        signed = 1
